version: 2

sources:
  - name: raw
    database: intense-pixel-490219-h2
    schema: raw

    loaded_at_field: ingestion_timestamp

    freshness:
      warn_after: {count: 24, period: hour}
      error_after: {count: 48, period: hour}

    tables:
      - name: customers
      - name: orders
      - name: order_items
      - name: payments
      - name: shipments
      - name: products